version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: trade_system_app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=trade_system
            - DB_USERNAME=root
            - DB_PASSWORD=123 # Password for MySQL root user
        volumes:
            - .:/var/www
        command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.0
        container_name: trade_system
        environment:
            MYSQL_DATABASE: trade_system
            MYSQL_ROOT_PASSWORD: 123 # Root password for MySQL
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
